# Site title and subtitle. This is used in _includes/header.html
title: 'Collective Intelligence Framework'
subtitle: "massive-octo-spice"

# URL to source code, used in _includes/footer.html
codeurl: 'https://github.com/csirtgadgets/massive-octo-spice'
siteurl: 'https://csirtgadgets.github.io/massive-octo-spice' 
baseurl: '/massive-octo-spice'
#siteurl: 'http://0.0.0.0:4000'

# Exclude non-site files
exclude: ['bin', 'README.md']

post_limit: 7 

sections: [
    ['doc', 'Documentation'],
    ['tut', 'Tutorial'],
    ['ref', 'Reference'],
    ['dev', 'Developers'],
    ['post', 'Posts'],
    ['plat', 'Platform'],
    ['api', 'API']
]

# Use the redcarpet Markdown renderer
markdown: redcarpet
redcarpet:
    extensions: [
        'no_intra_emphasis',
        'fenced_code_blocks',
        'autolink',
        'strikethrough',
        'superscript',
        'with_toc_data',
        'tables',
        'hardwrap'
    ]
gems:
    - jekyll-mentions
